name: Aggiorna GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Genera badge GitHub Stats
        run: |
          mkdir -p assets
          # USA IL TUO NUOVO URL QUI
          curl -o assets/github-stats.svg "https://github.com/antoniotraversa/github-readme-stats/api?username=antoniotraversa&show_icons=true&locale=it&theme=gotham&bg_color=212121&title_color=F7B23B&text_color=FFFFFF&icon_color=4CAF50&count_private=true"
          # E ANCHE QUI
          curl -o assets/github-langs.svg "https://github.com/antoniotraversa/github-readme-stats/api/top-langs/?username=antoniotraversa&layout=compact&locale=it&theme=gotham&bg_color=212121&title_color=F7B23B&text_color=FFFFFF&count_private=true"

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-stats.svg assets/github-langs.svg
          if ! git diff-index --quiet HEAD; then
            git commit -m "📈 Aggiorna badge GitHub Stats"
            git pull --rebase
            git push
          else
            echo "Nessuna modifica da committare."
          fi