name: Aggiorna GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # ogni giorno a mezzanotte
  workflow_dispatch:     # permette di lanciare manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Aggiorna badge GitHub Stats
      run: |
        # Esempio: genera badge con token in locale
        curl -o assets/github-stats.svg "https://github-readme-stats.vercel.app/api?username=antoniotraversa&show_icons=true&theme=gotham&bg_color=212121&title_color=F7B23B&text_color=FFFFFF&icon_color=4CAF50&access_token=${{ secrets.GH_TOKEN }}"

        curl -o assets/github-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=antoniotraversa&layout=compact&theme=gotham&bg_color=212121&title_color=F7B23B&text_color=FFFFFF&access_token=${{ secrets.GH_TOKEN }}"

    - name: Commit e push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add assets/github-stats.svg assets/github-langs.svg
        git commit -m "Aggiorna badge GitHub Stats"
        git push
